#! /bin/bash
npm init -y;
npm install typescript --save-dev;
npm install @types/node --save-dev;
npx tsc --init --rootDir src --outDir Dist --esModuleInterop --resolveJsonModule --lib es6 --module commonjs --allowJs true --noImplicitAny true;
npm install --save-dev ts-node nodemon;
npm install --save-dev rimraf;
echo '{
        "watch": ["src"], 
        "ext": ".ts,.js", 
        "ignore": [], 
        "exec": "npx ts-node ./src/index.ts"
}' >> nodemon.json; 
sed -i '/"scripts": {/a "start:dev": "npx nodemon",' package.json;
sed -i '/"scripts": {/a "build": "rimraf ./dist && tsc",' package.json;
sed -i '/"scripts": {/a "start": "npm run build && node dist/index.js",' package.json;
mkdir dist src;
touch ./src/index.ts;


